# Generated by Django 4.1 on 2022-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
