# Generated by Django 4.1 on 2022-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_bdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='c@ya.ru', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='f_name',
            field=models.CharField(default='1', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='l_name',
            field=models.CharField(default='1', max_length=64),
        ),
    ]
