# Generated by Django 4.1 on 2022-09-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_creator_alter_campaign_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='campaigns.campaign')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='campaigns.house')),
            ],
        ),
    ]
