# Generated by Django 4.1 on 2022-09-06 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_checkup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staircase', models.IntegerField()),
                ('number', models.IntegerField()),
                ('size', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_house', to='campaigns.house')),
            ],
        ),
        migrations.CreateModel(
            name='CheckupResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(blank=True)),
                ('open_door', models.BooleanField()),
                ('opinion', models.CharField(blank=True, max_length=64)),
                ('c_name', models.CharField(blank=True, max_length=64)),
                ('c_phone', models.CharField(blank=True, max_length=64)),
                ('comments', models.TextField(blank=True)),
                ('apart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='campaigns.apartment')),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason', to='campaigns.checkup')),
            ],
        ),
    ]
