# Generated by Django 4.1 on 2022-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_apartment_checkupresults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkupresults',
            options={'verbose_name': 'CheckupResults', 'verbose_name_plural': 'CheckupResults_list'},
        ),
        migrations.AlterField(
            model_name='checkupresults',
            name='open_door',
            field=models.BooleanField(default=False),
        ),
    ]
